---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 2990890577-yBrWkKvoxqVK4reb8ZCRYVAVbvdwyCaeGFe6b5R
:access_token_secret: rCOLrpHd6mPg7beFGrHi5wYAOuZyryi5gMQ8VpusytIIZ
